language: php

dist: trusty

matrix:
  include:
    - php: 7
    - php: 7.1
    - php: 7.2

before_script:
  - composer require silverstripe/recipe-core:1

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml tests/

after_script:
  - bash <(curl -s https://codecov.io/bash)
