language: php

dist: trusty

matrix:
  include:
    - php: 7
    - php: 7.1
    - php: 7.2

before_script:
  - composer require silverstripe/recipe-testing:^1 silverstripe/recipe-cms:^1

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
